# Generated by Django 3.0.3 on 2020-02-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('aid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=15)),
                ('eaddress', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('saddress', models.CharField(max_length=50)),
                ('venderFlag', models.IntegerField(choices=[(0, 'customer'), (1, 'vendor')])),
            ],
            options={
                'db_table': 'account_info',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'product_info',
            },
        ),
        migrations.CreateModel(
            name='properties',
            fields=[
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ISI.product')),
                ('author', models.CharField(max_length=15)),
                ('numPage', models.IntegerField()),
                ('publisher', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'properties_info',
            },
        ),
        migrations.CreateModel(
            name='purchOrder',
            fields=[
                ('po', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pDate', models.DateField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('p', 'pending'), ('h', 'hold'), ('s', 'shipped'), ('c', 'cancelled')], max_length=1)),
                ('specDate', models.DateField()),
                ('cancelledPerson', models.CharField(choices=[('c', 'customer'), ('v', 'vendor')], max_length=1)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISI.account')),
            ],
            options={
                'db_table': 'purchOrder_info',
            },
        ),
        migrations.CreateModel(
            name='shopcartRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISI.account')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISI.product')),
            ],
            options={
                'db_table': 'shopcartRecord_info',
                'unique_together': {('pid', 'aid')},
            },
        ),
        migrations.CreateModel(
            name='dorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rName', models.CharField(max_length=15)),
                ('rAddress', models.CharField(max_length=50)),
                ('rQuentity', models.IntegerField()),
                ('rPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ISI.product')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISI.purchOrder')),
            ],
            options={
                'db_table': 'dorder_info',
                'unique_together': {('po', 'pid')},
            },
        ),
    ]
