# Generated by Django 3.0.3 on 2020-02-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISI', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='thumbnail_image',
        ),
    ]
