# Generated by Django 3.0.3 on 2020-02-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISI', '0005_auto_20200211_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
