# Generated by Django 3.0.3 on 2020-02-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISI', '0007_auto_20200213_0342'),
        ('ISI', '0006_auto_20200212_2123'),
    ]

    operations = [
    ]
