# Generated by Django 3.0.3 on 2020-03-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISI', '0008_merge_20200213_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.TextField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISI.product')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISI.purchOrder')),
            ],
            options={
                'db_table': 'review_info',
            },
        ),
    ]
